import {
  Award,
  BadgeCheck,
  Cake,
  Camera,
  Clock,
  Coffee,
  CreditCard,
  Flower2,
  Gem,
  Gift,
  Globe,
  Handshake,
  Headphones,
  Heart,
  Home,
  Leaf,
  Lightbulb,
  Lock,
  MapPin,
  MessageCircle,
  Package,
  Palette,
  PhoneCall,
  RefreshCw,
  Rocket,
  Scissors,
  Shield,
  ShoppingBag,
  Smile,
  Sparkles,
  Star,
  Store,
  Tag,
  ThumbsUp,
  Truck,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** The icon set offered in the builder's icon picker. */
export const SECTION_ICONS: Record<string, LucideIcon> = {
  star: Star,
  heart: Heart,
  truck: Truck,
  shield: Shield,
  sparkles: Sparkles,
  package: Package,
  gift: Gift,
  tag: Tag,
  award: Award,
  "badge-check": BadgeCheck,
  clock: Clock,
  "credit-card": CreditCard,
  leaf: Leaf,
  gem: Gem,
  flower: Flower2,
  scissors: Scissors,
  wrench: Wrench,
  camera: Camera,
  cake: Cake,
  coffee: Coffee,
  palette: Palette,
  users: Users,
  handshake: Handshake,
  headphones: Headphones,
  "message-circle": MessageCircle,
  "phone-call": PhoneCall,
  "map-pin": MapPin,
  store: Store,
  "shopping-bag": ShoppingBag,
  home: Home,
  globe: Globe,
  lock: Lock,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  lightbulb: Lightbulb,
  smile: Smile,
  "thumbs-up": ThumbsUp,
  zap: Zap,
};

export const ICON_KEYS = Object.keys(SECTION_ICONS);

export function iconFor(name?: string): LucideIcon {
  return SECTION_ICONS[name ?? ""] ?? Star;
}
